import 'package:flutter/material.dart';

class HistoryDokter {
  final String images, name, department, tahun, str, status, tanggal;
  HistoryDokter(
      {required this.images,
      required this.name,
      required this.department,
      required this.tahun,
      required this.str,
      required this.status,
      required this.tanggal});
}

List<HistoryDokter> histories = [
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
  HistoryDokter(
      images: 'assets/images/dokter.png',
      name: 'Dr. Lutfhi',
      department: 'Dokter Umum',
      tahun: '2 Tahun',
      str: 'STR',
      status: 'completed',
      tanggal: '20 Mei 2022'),
];
